START TRANSACTION;
CREATE DATABASE IF NOT EXISTS `migrations`;
USE `migrations`;

CREATE TABLE IF NOT EXISTS `absolute` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `executed_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
